### PR TITLE
Rename `Object` -> `Obj` as it is now a reserved word in php 7.2

### PR DESCRIPTION
**Pull request by trq**
I am starting this PR to get a conversation started as to how this would be best dealt with moving forward. Basically, in order for us to continue to use both `predaddy` and `precore` and move forward with php 7.2 I needed to rename the current `precore\lang\Object` to `precore\lang\Obj` because `Object` is now a reserved word.

This is fine, I forked your projects and went ahead and started making the change. The issue I ran into was when I installed the dependencies required to run the test suite.

There are numerous issues with some of the libraries required to run the tests. The first I ran into was an issue within `lisachenko/go-aop-php`. This package has (at the version 0.5.0 that precore requires) also got issues working with php 7. This package has since moved to a new organisation (`goaop/framework`), and fixed those errors, however, it has become pretty clear that we need to invest a fair bit more effort to bring `precore` and `predaddy` up to date.

To get things working for us temporarily, I have created our own forks, fixed the Object name issue and have ignored running the unit tests within this library itself, relying on our own (application level) unit tests instead. I also created some packages for these libraries on packagist (https://packagist.org/packages/glowteam).

There are a few questions that I have.

We are willing to commit to do the work that needs to be done to get this package updated to work with php 7 as we believe the library to be awesome! What I am however wondering is:

Would you be happy to have these changes merged back into your project, and would you be available/willing to merge these changes in as required?

Or

Would you simply prefer to move these packages into some other organisation and let us worry about them?

If you have any other ideas, please let me know.

### CODE REVIEW

**Comment by szjani** [comment]
Hello @trq 

I'm happy to hear you're still using this and all dependant libraries I built. I didn't put any effort into the maintenance, though I knew this day would come. :)
It would be great if these libraries could be updated to be compatible with the latest version of PHP. It would be also cool if at least the most important features introduced in PHP 7 were used such as return type hints. It's clear that backward compatibility cannot be kept so it may be the best time to re-consider these things.

I'll check your changes and all the issues you've mentioned and I'll also try to dedicate some time even this week to make these libraries 2018 compatible.

**Comment by trq** [comment]
Oh that's great news thanks Janos.

The changes in our repos are a bit of a quick hack to keep us moving forward. Ideally, I'd probably get rid of the `Object` class all together and replace it with a trait, to try and keep the inheritance tree a bit smaller. It's a shame php still doesn't have multiple inheritance.

You will notice that I also changed the composer file so that we could pull precore and predaddy in from our own namespace on packagist. If your still keen to move ahead, then you'll likely want to revert that, and we can start pulling from your packagist namespace again once things are working.

Maybe you could setup these packages within an organisation in github that we could both get access too? Might just make thing easier moving forward.

I'll go ahead and make another PR now on the predaddy side as I've already gone ahead and renamed all references to `Object` there too.

**Comment by szjani** [comment]
I've done a lot of changes in precore. It is PHP 7.1 compatible now and also uses some of those new shiny features. I hope you don't mind I've done it from the scratch since I wanted a bigger update, not just quick fix.
It can be found here: https://github.com/szjani/precore/tree/feature/make-php-7-1-compatible

I'm going to check predaddy and lf4php as well in the upcoming days. I don't release precore until those are already updated.

Any feedback is welcome.

**Comment by szjani** [comment]
The requested compatibility issue has been fixed.

**Pull request closed without merging**
